import fs from 'node:fs';import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)).replace(/\/$/,'');
const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{style:{setProperty(){}},addEventListener(){},setPointerCapture(){},getBoundingClientRect:()=>({left:0,top:0,width:104,height:104})});return elements.get(id)};
globalThis.innerWidth=390;globalThis.innerHeight=844;globalThis.devicePixelRatio=1;
globalThis.document={body:{prepend(){}},getElementById:el,createElement:()=>({getContext:()=>new Proxy({},{get:()=>()=>{}})})};globalThis.addEventListener=()=>{};
let src=fs.readFileSync(root+'/public/neon/district.js','utf8');
src=src.replace("import * as THREE from '../crimson/lib/three.module.min.js';",`import * as Real from 'file://${root}/public/crimson/lib/three.module.min.js';const THREE={...Real,WebGLRenderer:class{constructor(){this.domElement={}}setPixelRatio(){}setSize(){}render(s,c){s.updateMatrixWorld();c.updateMatrixWorld()}}};`);
const {District}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
const d=new District();const enemy={boss:false,phase:'windup',timer:1,period:1.5,dir:0,hit:0};
assert.ok(d.batchStats.before>100);assert.ok(d.batchStats.after<60);assert.ok(d.batchStats.after<d.batchStats.before/5);assert.equal(d.collides(-14,-13),true);assert.equal(d.collides(0,0),false);
d.placeEnemy(enemy);assert.equal(d.canStrike(),false);d.keys.add('KeyW');for(let i=0;i<10;i++)d.update(.04,true,enemy);assert.ok(d.position.z<8);assert.equal(d.canStrike(),true);
d.yaw=Math.PI;assert.equal(d.canStrike(),false);d.update(.02,false,enemy);assert.equal(d.keys.size,0);assert.equal(d.move.x,0);
d.reset();d.position.set(-8,1.65,-13);d.keys.add('KeyA');for(let i=0;i<100;i++)d.update(.04,true,enemy);assert.equal(d.collides(d.position.x,d.position.z),false);
let pickups=0;d.onPickup=()=>pickups++;d.position.set(-23,1.65,5);d.clearInput();d.update(.02,true,enemy);assert.equal(pickups,1);d.update(.02,true,enemy);assert.equal(pickups,1);
innerWidth=844;innerHeight=390;d.resize();assert.equal(d.camera.aspect,844/390);
const colors=Object.values(d.materials).map(m=>m.color.getHex());d.setStyle('rick-morty');assert.equal(d.portal.visible,true);assert.equal(d.ink.visible,true);assert.equal(d.alienEyes.visible,true);d.setStyle('ghibli');assert.deepEqual(Object.values(d.materials).map(m=>m.color.getHex()),colors);assert.equal(d.portal.visible,false);
function travel(hz){d.reset();d.actor.visible=false;d.keys.add('KeyW');for(let i=0;i<hz;i++)d.update(1/hz,true,null);return 8-d.position.z}
assert.ok(Math.abs(travel(60)-10.5)<.001);assert.ok(Math.abs(travel(30)-travel(60))<.001);assert.ok(Math.abs(travel(15)-travel(60))<.001);
d.reset();d.actor.visible=false;d.position.set(-8,1.65,-13);d.keys.add('KeyA');for(let i=0;i<20;i++)d.update(.1,true,null);assert.equal(d.collides(d.position.x,d.position.z),false);
console.log('Scenery batches:',d.batchStats);
console.log('PASS: real Three scene construction, walk movement, building collision, approach/range/facing gates, pause reset, pickup debounce, viewport resize. GPU renderer mocked.');
