#!/bin/sh
# Deletes 123 branches already merged into main. Run from a clone of vdimarco/rouge-warden.
set -e
git push origin --delete \
ccr-38123011-6zy79i \
ccr-83ea9311-tzr2up \
ccr-90153085-d10aau \
ccr-b0d7048a-3ejwai \
ccr-e1dd68a0-6warww \
ccr-e1dd68a0-6warww-tested \
chore/remove-combat-fun-qa-workflow \
claude/amazing-ramanujan-a6h28o \
claude/cool-lovelace-wy420l \
claude/dazzling-cerf-1ju5dm \
claude/focused-fermi-bzlkxy \
claude/follow-suit-prototype-0fyikv \
claude/hopeful-allen-hkt7mb \
claude/lucid-ritchie-q3y7n5 \
claude/nifty-gates-bjgt6l \
codex/active-celestial-rallies \
codex/all-games-machines \
codex/brawl-chaos-hero \
codex/canyon-fleet-finish \
codex/celestial-upgrade-console \
codex/cottage-brawl-arcade \
codex/crimson-rogue-labels \
codex/echo-family-crossing \
codex/echo-rescue-chase \
codex/fishing-direct-rod \
codex/fishing-ghibli-style \
codex/fishing-motion-guide \
codex/fishing-optional-fullscreen \
codex/fishing-painted-film \
codex/fishing-pull-back-demo \
codex/fishing-pull-strength \
codex/fishing-reel-side \
codex/fix-echo-asset-paths \
codex/full-tilt-celestial-landscape \
codex/full-tilt-reverse-scoop-warp \
codex/gabe-bear-fal \
codex/gabe-epilogue-motion \
codex/lake-cartoon-look \
codex/lake-higgsfield-art \
codex/loon-echo-prototype \
codex/moba-base-attacks \
codex/moba-combat-decisions \
codex/moba-epic-opening \
codex/moba-fal-opening-art \
codex/moba-hero-classes \
codex/moba-hero-skill-wheel \
codex/moba-mouse-targeting \
codex/moba-reference-upgrades \
codex/moba-roster-ui \
codex/moba-skill-notice \
codex/moba-swipe-heroes \
codex/moba-tactical-combat \
codex/moba-unboxed-heroes \
codex/neon-blade-duels-404 \
codex/neon-handle-pivot \
codex/neon-ninja-speed-styles \
codex/neon-open-district \
codex/neon-patrol-tablet \
codex/neon-phone-view \
codex/neon-photoreal-view \
codex/neon-physical-sword \
codex/neon-ronin-gyro \
codex/organic-space-pinball \
codex/pinball-adventure \
codex/pinball-browser-tests \
codex/pinball-cinematic-transit \
codex/pinball-gentle-tilt \
codex/pinball-gravity-wells \
codex/pinball-left-hand-keys \
codex/pinball-warp-release-notes \
codex/pinball-warp-surf \
codex/sedona-surface-mouth-audio \
codex/shared-procedural-creatures \
codex/shore-landscape-layout \
codex/shore-reference-selection \
codex/six-mobile-worlds \
codex/tidebreak-mobile-moba \
crimson-wanted-merge \
cursor/breakthrough-cabinet-current-d487 \
cursor/breakthrough-visual-upgrade-ef18 \
cursor/breakthrough2-art-pack-153f \
cursor/breakthrough2-climate-roguelike-ce09 \
cursor/breakthrough2-pathways-9539 \
cursor/breakthrough2-trajectory-9fb1 \
cursor/howto-motion-153f \
cursor/tell-me-toy-bb0d \
cursor/tellme-qa-fixes-cf58 \
docs/openspec-workflow \
feat/bolder-pond-water \
feat/compact-multitouch-fal-icons \
feat/compact-skills-multitouch-upgrade \
feat/crimson-realistic-voices \
feat/easier-skill-controls-fal-icons \
feat/fishing-pond-water \
feat/group-arcade-lab \
feat/moba-touch-abilities \
feat/moba-touch-ability-icons \
feat/mobile-swing-motion \
feat/neon-mobile-ronin-model \
feat/neon-portal-badlands \
feat/neon-stable-horizon-fal-world \
feat/olympus-isometric-depth \
feat/olympus-painted-art \
feat/shore-better-ability-controls \
feat/shore-of-the-ancients-menu \
feat/shore-selection-screen \
feat/tap-ability-to-upgrade \
feat/water-city-depth \
feature/breakthrough-climate-roguelike \
fix/fishing-forward-water \
fix/fishing-line-dynamics \
fix/neon-comfortable-grip \
fix/neon-desktop-mouse-sword \
fix/neon-generation-diagnostics \
fix/neon-image-to-mesh \
fix/neon-resume-generated-ronin \
fix/olympus-diagonal-speed \
fix/olympus-sprite-shadows \
fix/one-hand-swing-city \
fix/shore-selection-screen \
neon-enemy-evasion \
neon-mouse-view-weapon \
studio/merged-pr-state
git fetch --prune origin
