const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const crypto = require('node:crypto');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const token = 'a'.repeat(64);
const config = { tokenSha256: crypto.createHash('sha256').update(token).digest('hex'), expiresAt: '2099-01-01T00:00:00Z', idempotency: { ghibli: 'fixed-ghibli', pixar: 'fixed-pixar', 'rick-and-morty': 'fixed-rick' } };
const env = { VERCEL_ENV: 'preview', HIGGSFIELD_API_KEY: 'test-key', HIGGSFIELD_API_SECRET: 'test-secret' };
const calls = [];
let response = { status: 'queued', request_id: '11111111-1111-4111-8111-111111111111' };
let httpStatus = 200;
const context = { module: { exports: {} }, Buffer, URL, AbortSignal, process: { env }, require: name => name === 'node:crypto' ? crypto : name.endsWith('style-session.json') ? config : require(path.join(root, 'higgsfield/monster-styles.json')), fetch: async (url, options) => { calls.push({ url, options }); return { ok: httpStatus === 200, status: httpStatus, json: async () => response }; } };
vm.runInNewContext(fs.readFileSync(path.join(root, 'api/monster-style-session.js'), 'utf8'), context);
async function invoke(method, query = {}, body, auth = `Bearer ${token}`) {
  const res = { code: 200, headers: {}, setHeader(k, v) { this.headers[k] = v; }, status(code) { this.code = code; return this; }, json(data) { this.data = JSON.parse(JSON.stringify(data)); return this; } };
  await context.module.exports({ method, query, body, headers: { authorization: auth } }, res);
  return res;
}
(async () => {
  assert.equal((await invoke('POST', {}, { style: 'ghibli' }, '')).code, 401);
  assert.equal(calls.length, 0);
  env.VERCEL_ENV = 'production';
  assert.equal((await invoke('GET', { action: 'config' })).code, 410);
  env.VERCEL_ENV = 'preview';
  config.expiresAt = '2000-01-01T00:00:00Z';
  assert.equal((await invoke('GET', { action: 'config' })).code, 410);
  config.expiresAt = '2099-01-01T00:00:00Z';
  delete env.HIGGSFIELD_API_SECRET;
  assert.equal((await invoke('GET', { action: 'config' })).code, 503);
  env.HIGGSFIELD_API_SECRET = 'test-secret';
  assert.equal((await invoke('POST', {}, { style: '__proto__' })).code, 400);
  assert.equal((await invoke('POST', {}, { style: 'pixar', model: 'another' })).code, 400);
  assert.equal((await invoke('GET', { action: 'status', id: '../models' })).code, 400);
  assert.equal(calls.length, 0);
  await invoke('POST', {}, { style: 'ghibli' });
  await invoke('POST', {}, { style: 'ghibli' });
  assert.equal(calls[0].url, 'https://api.higgsfield.ai/marketing-studio/image');
  assert.equal(calls[0].options.headers.Authorization, 'Key test-key:test-secret');
  assert.equal(calls[0].options.headers['Idempotency-Key'], calls[1].options.headers['Idempotency-Key']);
  assert.equal(calls[0].options.body, calls[1].options.body);
  assert.equal(calls[0].options.redirect, 'error');
  httpStatus = 401;
  const rejection = await invoke('POST', {}, { style: 'pixar' });
  assert.deepEqual(rejection.data, { error: 'higgsfield_rejected', upstreamStatus: 401 });
  assert.equal(JSON.stringify(rejection.data).includes('test-secret'), false);
  httpStatus = 200;
  response = { status: 'completed', images: [{ url: 'https://cdn.example.com/image.png' }, { url: 'http://bad.test/image.png' }, { url: 'https://secret@bad.test/image.png' }] };
  const result = await invoke('GET', { action: 'status', id: '11111111-1111-4111-8111-111111111111' });
  assert.deepEqual(result.data.images, [{ url: 'https://cdn.example.com/image.png' }]);
  console.log('PASS: authentication, expiry, preview restriction, fixed inputs, idempotency, secret-safe errors, safe output URLs.');
})().catch(e => { console.error(e); process.exitCode = 1; });
