'use client';
import {useEffect,useRef,useState} from 'react';
import {Game,type Snapshot} from '@/lib/game/engine';
import {blessings} from '@/lib/game/content';
import {relics,relicCost} from '@/lib/game/progression';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Pause,Volume2,VolumeX,Maximize,Flame,Play,RotateCcw,ArrowUp,ArrowLeft,Anvil} from 'lucide-react';
const clock=(n:number)=>Number.isFinite(n)?`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`:'--:--';
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),game=useRef<Game|null>(null);
 const [s,setS]=useState<Snapshot|null>(null),[sound,setSound]=useState(false),[help,setHelp]=useState(false),[fullscreenError,setFullscreenError]=useState('');
 useEffect(()=>{const g=new Game(canvas.current!,setS);game.current=g;return()=>g.destroy()},[]);
 const start=()=>game.current?.start();const mode=s?.mode??'title';
 const fullscreen=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{setFullscreenError('Use your browser menu to add Olympus to your home screen.')}};
 const onSound=()=>setSound(game.current?.toggleSound()??false);
 return <main className="game-shell">
  <canvas ref={canvas} aria-label="Olympus survival arena. Drag anywhere to move. Weapons fire automatically. Keyboard: WASD or arrow keys. P pauses." tabIndex={0}/>
  {!['title','forge'].includes(mode)&&<header className="hud">
   <div className="experience" role="progressbar" aria-label="Progress to next level" aria-valuenow={s?.xp??0} aria-valuemax={s?.need??14}><span style={{width:`${Math.min(100,(s?.xp??0)/(s?.need??1)*100)}%`}}/></div>
   <div className="hud-row"><div className="health-block"><div className="health"><span style={{width:`${(s?.hp??100)/(s?.maxHp??100)*100}%`}}/></div><span>{s?.hp} / {s?.maxHp}</span></div><strong className="timer">{clock(s?.time??0)}</strong><Button variant="ghost" className="square" aria-label="Pause game" onClick={()=>game.current?.pause()}><Pause size={19}/></Button></div>
   <div className="hud-details"><span>LV {s?.level} · {s?.xp}/{s?.need}</span><span>{s?.kills} FREED</span><span>WAVE {s?.wave}</span></div>
   <div className="wave-track"><span className={s?.phase==='ONSLAUGHT'?'danger':''}>{s?.phase}</span><span>{s?.boss?'DODGE THE MARKED ATTACKS':`GUARDIAN IN ${clock(s?.nextBoss??90)}`}</span></div>
   {!!s?.boss&&<div className="boss"><span>{s.bossName}</span><div><i style={{width:`${s.boss*100}%`}}/></div></div>}
  </header>}
  {mode==='title'&&<section className="title-screen">
   <div className="title-top"><Flame size={21}/><a className="arcade-back" href="/">← ARCADE</a><button onClick={()=>setHelp(true)}>How to play</button></div>
   <div className="title-heading"><h1>OLYMPUS</h1><div className="subtitle"><span/>LAST FLAME<span/></div><p>Every wave is earned.</p></div>
   <div className="hero-art"><img className="breathing-hero" src="/olympus/art/hero-8.png" alt="The bearer of Prometheus’ flame"/><img className="hero-flame" src="/olympus/art/sprite-7.png" alt=""/></div>
   <div className="title-bottom"><div className="run-goal"><span>YOUR NEXT TRIAL</span><strong>{s?.legacy.bestRealm?`Push beyond realm ${s.legacy.bestRealm}`:'Defeat the first guardian'}</strong><p>Three waves. Ninety seconds. Fight your way through.</p></div><Button className="gold-button" onClick={start}><Flame size={20}/> BEGIN THE ASCENT</Button><Button variant="outline" className="forge-button" onClick={()=>game.current?.openForge()}><Anvil size={16}/> THE FORGE <span>{s?.legacy.embers??0} embers</span></Button><span className="control-note">Drag to move · attacks fire automatically</span>{!!s?.best&&<span className="best">LONGEST RUN {clock(s.best)}</span>}</div>
   <footer><span>ONE THUMB · NO SECOND CHANCES</span><button onClick={onSound} aria-label={sound?'Mute audio':'Enable audio'}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></footer>
  </section>}
  {mode==='play'&&<><div className="realm">REALM {s?.realmNumber} · {s?.realm}</div>{s?.notice&&<div className="notice" role="status">{s.notice}</div>}<div className="loadout">{blessings.filter(b=>(s?.powers[b.id]??0)>0).map(b=><div key={b.id} title={`${b.name} ${s?.powers[b.id]}`} style={{color:b.color}}><span>{b.symbol}</span><small>{s?.powers[b.id]}</small></div>)}</div><div className="ember-counter"><Flame size={13}/>{s?.earned} earned</div>{s?.evolution&&<div className="evolution">{s.evolution}</div>}</>}
  <Dialog open={mode==='blessing'}><DialogContent className="blessing-panel" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}>
   <div className="modal-level">LEVEL {s?.level} · A GIFT EARNED</div><DialogTitle className="modal-title">Choose your strength.</DialogTitle><DialogDescription className="modal-description">Each blessing lasts for this run. Choose carefully.</DialogDescription>
   <div className="blessings">{s?.choices.map(id=>{const b=blessings.find(b=>b.id===id)!;return <button className="blessing" key={id} style={{'--god-color':b.color} as React.CSSProperties} onClick={()=>game.current?.choose(id)}><span className="god-symbol">{b.symbol}</span><span><small>{b.god} · {s.powers[id]>0?`RANK ${s.powers[id]+1} / 5`:'NEW POWER'}</small><strong>{b.name}</strong><p>{b.description}</p></span><span className="pick-arrow">›</span></button>})}</div>
   <button className="reroll" disabled={!s?.rerolls} onClick={()=>game.current?.reroll()}>↻ {s?.rerolls?'Reroll · once per run':'Reroll used'}</button><p className="recipe">Evolutions: Flame IV + Ares II · Zeus IV + Poseidon II</p>
  </DialogContent></Dialog>
  <Dialog open={mode==='pause'} onOpenChange={v=>{if(!v)game.current?.pause()}}><DialogContent className="pause-panel" showCloseButton={false}>
   <DialogTitle className="modal-title">A moment of stillness.</DialogTitle><DialogDescription className="modal-description">{s?.earned} embers secured so far. Resume to keep climbing.</DialogDescription><Button className="gold-button" onClick={()=>game.current?.pause()}><Play size={18}/> RESUME JOURNEY</Button><div className="settings-row"><Button variant="outline" onClick={onSound}>{sound?<Volume2/>:<VolumeX/>} Sound {sound?'on':'off'}</Button><Button variant="outline" onClick={fullscreen}><Maximize/> Full screen</Button></div>{fullscreenError&&<p className="modal-description">{fullscreenError}</p>}<p className="director-status">{s?.director}</p><p className="connection-note">Keep moving. Blue souls give XP. Red fruit restores health.</p><Button variant="ghost" onClick={()=>{game.current?.bank();start()}}><RotateCcw/> Bank embers and restart</Button>
  </DialogContent></Dialog>
  <Dialog open={mode==='dead'||mode==='won'}><DialogContent className="death-panel" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}>
   <img src="/olympus/art/sprite-7.png" className="death-flame" alt=""/><DialogTitle className="modal-title">{mode==='won'?'The fire returns home.':'Even legends fall.'}</DialogTitle><DialogDescription className="modal-description">{mode==='won'?'Your embers are safe. Prepare for a deeper run.':s?.deathReason}</DialogDescription><div className="results"><div><strong>{clock(s?.time??0)}</strong><span>SURVIVED</span></div><div><strong>{s?.kills}</strong><span>SOULS FREED</span></div><div><strong>{s?.level}</strong><span>LEVEL</span></div></div><div className="reward-line"><Flame size={19}/> +{s?.earned} EMBERS KEPT</div><p className="modal-description">{s?.earned?'Spend them at the forge. Small gains stay with you.':`Survive a full 30-second wave to earn your first ember.`}</p><Button className="gold-button" onClick={start}><RotateCcw size={18}/> CLIMB AGAIN</Button><Button className="forge-button" variant="outline" onClick={()=>game.current?.openForge()}><Anvil size={16}/> VISIT THE FORGE <span>{s?.legacy.embers??0} embers</span></Button><p className="best">LONGEST RUN {clock(s?.best??0)}</p>{s&&!s.storageOk&&<p className="connection-note">This browser could not save your progress. Keep this tab open.</p>}
  </DialogContent></Dialog>
  <Dialog open={mode==='gate'}><DialogContent className="death-panel" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}>
   <div className="modal-level">REALM {s?.realmNumber} CLEARED</div><DialogTitle className="modal-title">A gate opens.</DialogTitle><DialogDescription className="modal-description">The next realm is harder. Ascend to restore 25 health and keep your blessings.</DialogDescription><div className="reward-line"><Flame/> {s?.earned} EMBERS SECURED</div><Button className="gold-button" onClick={()=>game.current?.ascend()}><ArrowUp/> ASCEND TO REALM {(s?.realmNumber??1)+1}</Button><Button className="forge-button" variant="outline" onClick={()=>game.current?.returnHome()}>Return home with your embers</Button>
  </DialogContent></Dialog>
  <Dialog open={mode==='forge'}><DialogContent className="pause-panel forge-panel" showCloseButton={false} onEscapeKeyDown={()=>game.current?.backToTitle()}>
   <div className="forge-heading"><Anvil/><span>{s?.legacy.embers??0} EMBERS</span></div><DialogTitle className="modal-title">The fire remembers.</DialogTitle><DialogDescription className="modal-description">Permanent upgrades. Saved on this device.</DialogDescription><div className="forge-list">{relics.map(r=>{const rank=s?.legacy.relics[r.id]??0,cost=relicCost(rank);return <div className="relic" key={r.id}><span className="relic-icon">{r.symbol}</span><div><strong>{r.name}</strong><p>{r.description}</p><span className="rank-pips" aria-label={`Rank ${rank} of 5`}>{Array.from({length:5},(_,i)=><i key={i} className={i<rank?'lit':''}/>)}</span></div><Button disabled={rank>=5||(s?.legacy.embers??0)<cost} onClick={()=>game.current?.buy(r.id)}>{rank>=5?'MAX':`${cost} ♨`}</Button></div>})}</div><Button className="gold-button" onClick={start}>BEGIN A NEW RUN</Button><Button variant="ghost" onClick={()=>game.current?.backToTitle()}><ArrowLeft size={16}/> Back</Button>{s&&!s.storageOk&&<p className="connection-note">Progress cannot be saved in this browser.</p>}
  </DialogContent></Dialog>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="pause-panel"><DialogTitle className="modal-title">Earn the ascent.</DialogTitle><DialogDescription className="modal-description">Drag with one thumb to move. Weapons aim and fire automatically.</DialogDescription><div className="instructions"><p><b>Fight close, then collect.</b> Your flame has limited range. Circle the enemies and sweep through blue souls to level up.</p><p><b>Read the attacks.</b> A red lane warns of a charge. Leave marked circles before they burst. Pink shots can be dodged.</p><p><b>Survive the wave.</b> Each 30-second wave earns one ember. A guardian arrives after ninety seconds. Defeat it to go deeper or return home.</p><p><b>Make progress between runs.</b> Embers survive death. Spend them on small permanent upgrades at the forge. Level-ups and blessings reset with each run.</p><p>Releasing your thumb briefly slows time, once every four seconds. Keyboard: WASD or arrows. P pauses.</p></div><Button className="gold-button" onClick={()=>setHelp(false)}>I’M READY</Button></DialogContent></Dialog>
 </main>
}
