import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';

const out = process.env.SHOTS || '/tmp/river-rush-qa'; await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1536, height: 1024 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto(process.env.GAME_URL || 'http://localhost:3000', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Start adventure' }).waitFor({ state: 'visible' });
await page.screenshot({ path: `${out}/menu-desktop.png` });
await page.getByRole('button', { name: 'How to play' }).click();
await page.getByRole('dialog', { name: 'How to play' }).waitFor();
await page.getByRole('button', { name: 'Let’s ride' }).click();
await page.waitForTimeout(1000);
await page.screenshot({ path: `${out}/game-desktop.png` });
const first = await page.locator('.timer').innerText();
await page.keyboard.press('Escape');
await page.getByRole('dialog', { name: 'Game paused' }).waitFor();
await page.waitForTimeout(1200);
const paused = await page.locator('.timer').innerText();
if (first !== paused) throw new Error(`Timer advanced while paused: ${first} vs ${paused}`);
await page.getByRole('button', { name: 'Resume adventure' }).click();
await page.keyboard.down('KeyA'); await page.waitForTimeout(400); await page.keyboard.up('KeyA');
await page.keyboard.down('Space'); await page.waitForTimeout(450); await page.keyboard.up('Space');
await page.getByRole('button', { name: 'Enable sound' }).click();
await page.getByRole('button', { name: 'Mute sound' }).click();
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Restart run' }).click();
if ((await page.locator('.timer').innerText()) !== '02:00') throw new Error('Restart did not reset timer');
await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'Back to river' }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: `${out}/menu-mobile.png`, fullPage: true });
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
if (overflow) throw new Error('Mobile horizontal overflow');
await page.getByRole('button', { name: 'Start adventure' }).click();
await page.waitForTimeout(350);
await page.screenshot({ path: `${out}/game-mobile.png` });
const right = await page.getByRole('button', { name: 'Steer right' }).boundingBox();
await page.mouse.move(right.x + right.width / 2, right.y + right.height / 2);
await page.mouse.down(); await page.waitForTimeout(100); await page.mouse.up();
if (errors.length) throw new Error(errors.join('\n'));
console.log(JSON.stringify({ passed: true, screenshots: out, checks: ['desktop menu', 'instructions', 'start', 'pause freezes timer', 'resume', 'steering', 'reach', 'audio toggles', 'restart', 'mobile layout', 'mobile game'], errors }));
await browser.close();
