import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const base = process.env.ARCADE_URL || 'http://localhost:8765/';
const out = process.env.SHOTS || '/tmp/river-rush-arcade-qa';
await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1536, height: 1024 } });
const errors = [], failed = [];
page.on('pageerror', e => errors.push(e.message));
page.on('response', r => { if (r.status() >= 400 && new URL(r.url()).origin === new URL(base).origin) failed.push(`${r.status()} ${r.url()}`); });
await page.goto(new URL('river-rush/', base).href, { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'Start adventure' }).waitFor();
assert.equal(await page.evaluate(() => document.querySelector('script').getAttribute('src')), '/arcade/quiet.js');
await page.getByRole('button', { name: 'Switch game' }).click();
await page.getByRole('dialog', { name: 'Switch game' }).waitFor({ state: 'visible' });
assert.equal(await page.locator('.gsw-game.here b').textContent(), 'River Rush');
await page.getByRole('button', { name: 'Keep playing' }).click();
await page.screenshot({ path: `${out}/menu-desktop.png` });
await page.getByRole('button', { name: 'Start adventure' }).click();
await page.waitForTimeout(2600);
await page.keyboard.down('KeyA'); await page.waitForTimeout(500); await page.keyboard.up('KeyA');
await page.waitForTimeout(2500);
await page.keyboard.down('Space'); await page.waitForTimeout(450); await page.keyboard.up('Space');
await page.screenshot({ path: `${out}/game-desktop.png` });
await page.locator('canvas').screenshot({ path: `${out}/cabinet-source.png` });
await page.keyboard.press('Escape');
await page.getByRole('dialog', { name: 'Game paused' }).waitFor();
const time = await page.locator('.timer').textContent(); await page.waitForTimeout(300);
assert.equal(await page.locator('.timer').textContent(), time);
await page.getByRole('button', { name: 'Back to river' }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: `${out}/menu-mobile.png` });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.getByRole('button', { name: 'Start adventure' }).click(); await page.waitForTimeout(250);
await page.screenshot({ path: `${out}/game-mobile.png` });
await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'Back to river' }).click();
await page.evaluate(() => localStorage.setItem('river-rush-best', JSON.stringify({ score: 2102, time: 94 })));
await page.goto(base, { waitUntil: 'domcontentloaded' });
assert.match(await page.locator('.cab[data-game="river-rush"] .hi').textContent(), /BEST 2,102 PTS/);
const option = await page.locator('#machinePicker option').evaluateAll(options => options.find(o => o.textContent === 'RIVER RUSH')?.value);
assert.ok(option); await page.locator('#machinePicker').selectOption(option);
await page.waitForTimeout(650);
assert.equal(await page.locator('.cab.on').getAttribute('data-game'), 'river-rush');
await page.screenshot({ path: `${out}/cabinet-mobile.png` });
await page.locator('.cab[data-game="river-rush"]').click();
await page.waitForURL('**/river-rush/');
await page.getByRole('button', { name: 'Start adventure' }).waitFor();
await page.evaluate(() => localStorage.setItem('river-rush-best', 'broken JSON'));
await page.reload(); await page.getByRole('button', { name: 'Start adventure' }).waitFor();
await page.goto(base); assert.equal(await page.locator('.cab[data-game="river-rush"] .hi').textContent(), 'CLAIM THE TREASURE');
for (const value of ['null', '{}', '{"score":0}', '{"score":-5}', '{"score":"2102"}', '{"score":1e999}']) {
  await page.evaluate(value => localStorage.setItem('river-rush-best', value), value);
  await page.reload();
  assert.equal(await page.locator('.cab[data-game="river-rush"] .hi').textContent(), 'CLAIM THE TREASURE');
}
assert.deepEqual(errors, []); assert.deepEqual(failed, []);
console.log(JSON.stringify({ passed: true, screenshots: out, checks: ['game subpath assets', 'first quiet script', 'shared switcher identity', 'keyboard steering and reach', 'pause freezes timer', 'desktop and phone', 'saved score', 'cabinet launch', 'junk-save fallback'], errors, failed }));
await browser.close();
