import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRequire} from 'node:module';
const {chromium}=createRequire(new URL('../../games/river-rush/package.json',import.meta.url))('playwright'),out=process.env.SHOTS||'/tmp/river-bank-lines',base=process.env.GAME_URL||new URL('river-rush/',process.env.ARCADE_URL||'http://127.0.0.1:8765/').href,stage=process.env.STAGE||'after';await fs.mkdir(out,{recursive:true});
const src=await fs.readFile(new URL('./wild-finale.mjs',import.meta.url),'utf8'),install=src.slice(src.indexOf('function install(){'),src.indexOf('const state=p=>'));
const report={passed:false,kind:'actual-App-Canopy-bank-lines',base,stage,stateOrClockMutations:false,rows:[],errors:[],physicalDeviceFrameRateMeasured:false};
const browser=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']});
try{
 const p=await browser.newPage();await p.addInitScript({content:`${install}\ninstall();localStorage.setItem('river-rush-sound-enabled','false');`});p.on('pageerror',e=>report.errors.push(e.message));
 for(const layout of [{name:'desktop',width:1536,height:1024},{name:'phone',width:390,height:844},...(stage==='after'?[{name:'landscape',width:844,height:390}]:[])]){
  if(process.env.CASE&&process.env.CASE!==layout.name)continue;await p.setViewportSize(layout);await p.goto(base);await p.waitForFunction(()=>{const b=document.querySelector('button[aria-label="Start run"]');return b&&!b.disabled;},{},{timeout:90000});const bundle=await p.evaluate(()=>[...document.scripts].map(s=>s.src).find(s=>s.includes('/river-rush/assets/index-')));if(process.env.EXPECTED_BUNDLE)assert.ok(bundle.endsWith(process.env.EXPECTED_BUNDLE));const prepared=await p.evaluate(()=>({...__resources}));
  await p.getByRole('button',{name:'Start run',exact:true}).click();await p.keyboard.press('ArrowLeft');await p.waitForFunction(async()=>(await __tools.get_run_status({})).run.lane===0);await p.keyboard.press('ArrowUp');await p.waitForFunction(async()=>(await __tools.get_run_status({})).run.action==='jump');await p.keyboard.press('ArrowDown');await p.waitForFunction(async()=>(await __tools.get_run_status({})).run.action==='duck');
  await p.waitForFunction(()=>__raw()?.distance>=100,{},{timeout:30000});await p.keyboard.press('Escape');await p.getByRole('dialog',{name:'Game paused'}).waitFor();const status=await p.evaluate(()=>__tools.get_run_status({}));assert.equal(status.run.level.id,'canopy');assert.equal(status.screen,'paused');assert.equal(status.run.lane,0);if(stage==='after'){assert.equal(status.renderer.world.falls,0);assert.equal(status.renderer.world.mist,0);assert.ok(status.renderer.world.cliffs>0);}
  const style=await p.addStyleTag({content:'dialog.modal{visibility:hidden}dialog.modal::backdrop{background:transparent;backdrop-filter:none}'});const screenshot=`${out}/app-${stage}-${layout.name}-canopy.png`;await p.screenshot({path:screenshot});const pixels=await p.locator('canvas').screenshot();await p.waitForTimeout(150);assert.deepEqual(await p.locator('canvas').screenshot(),pixels);assert.deepEqual(await p.evaluate(()=>__resources),prepared);assert.deepEqual(await p.evaluate(()=>__gpuErrors),[]);await style.evaluate(e=>e.remove());
  await p.getByRole('button',{name:'Resume run',exact:true}).click();await p.waitForFunction(async()=>{const s=await __tools.get_run_status({});return s.screen==='playing'&&s.run.distance>100;});await p.keyboard.press('Escape');await p.getByRole('dialog',{name:'Game paused'}).waitFor();report.rows.push({layout,bundle,status,screenshot,controls:['left lane','jump','duck','pause','resume'],pauseExactPixels:true,noActiveGpuPreparation:true});await fs.writeFile(`${out}/app-${stage}.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({layout:layout.name,stage,falls:status.renderer.world.falls,distance:status.run.distance,passed:true}));
 }
 assert.deepEqual(report.errors,[]);report.passed=true;await p.close();
}finally{await fs.writeFile(`${out}/app-${stage}.json`,JSON.stringify(report,null,2)+'\n');await browser.close();}
