import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
const {chromium}=createRequire(new URL('../../games/river-rush/package.json',import.meta.url))('playwright');
const base=process.env.GAME_URL||new URL('river-rush/',process.env.ARCADE_URL||'http://127.0.0.1:8765/').href;
const out=process.env.SHOTS||'/tmp/river-terrain-feedback',stage=process.env.STAGE||'after';await fs.mkdir(out,{recursive:true});
const audioSource=await fs.readFile(new URL('./epic-music.e2e.mjs',import.meta.url),'utf8');
let audioInstall=audioSource.slice(audioSource.indexOf('function observeAudio(){'),audioSource.indexOf('const status=p=>'));
audioInstall=audioInstall.replace('const rawConnect=AudioNode.prototype.connect,Base=', 'const rawConnect=AudioNode.prototype.connect;window.__nativeAudioConnect=rawConnect;const Base=');
const gpuSource=await fs.readFile(new URL('./wild-finale.mjs',import.meta.url),'utf8');
let gpuInstall=gpuSource.slice(gpuSource.indexOf('function install(){'),gpuSource.indexOf('const state=p=>'));
gpuInstall=gpuInstall.replace("window.__tools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.__tools[t.name]=t.execute;}}});",'');
const requireQuiet=await fs.readFile(new URL('../../public/arcade/quiet.js',import.meta.url),'utf8');
const report={passed:false,kind:'actual-App-contact-animation-and-audible-cues',base,stage,stateOrClockMutations:false,rows:[],errors:[],limits:['Headless Chromium/SwiftShader; no physical phone, speaker audition, or hardware FPS measurement.','Visibility events are emulated.']};
const browser=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']});
function observeCues(){
 window.__cueProbe={voices:[],frames:[],contacts:[],seen:new Set(),done:false};
 const native=window.__nativeAudioConnect,connect=AudioNode.prototype.connect;
 for(const Base of [OscillatorNode,AudioBufferSourceNode]){const start=Base.prototype.start;Base.prototype.start=function(...args){this.__qaStartedAt=args[0]??this.context.currentTime;this.__qaEnded=false;this.addEventListener('ended',()=>{this.__qaEnded=true;this.__qaEndedAt=this.context.currentTime;});return start.apply(this,args);};}
 const ancestors=(node,depth=0)=>{if(depth>4)return[];return __audioProbe.edges.filter(e=>e.to===node).flatMap(e=>[e.from,...ancestors(e.from,depth+1)]);};
 AudioNode.prototype.connect=function(destination,...args){const result=connect.call(this,destination,...args);if(this instanceof GainNode){
  const sources=ancestors(this).filter(n=>n instanceof OscillatorNode||n instanceof AudioBufferSourceNode&&!n.loop);
  if(sources.length){const analyser=this.context.createAnalyser(),sink=this.context.createGain();analyser.fftSize=1024;sink.gain.value=0;native.call(this,analyser);native.call(analyser,sink);native.call(sink,this.context.destination);__cueProbe.voices.push({source:sources[0],gain:this,analyser,ctx:this.context,peakRms:0,peakAt:null});}
 }return result;};
 window.__cueSnapshot=()=>__cueProbe.voices.map(v=>{let rms=0;if(v.ctx.state==='running'&&!v.source.__qaEnded&&v.ctx.currentTime>=(v.source.__qaStartedAt??Infinity)){const data=new Float32Array(v.analyser.fftSize);v.analyser.getFloatTimeDomainData(data);rms=Math.sqrt(data.reduce((sum,x)=>sum+x*x,0)/data.length);if(rms>v.peakRms){v.peakRms=rms;v.peakAt=v.ctx.currentTime;}}return{source:v.source instanceof OscillatorNode?'oscillator':'noise',wave:v.source.type??null,frequency:v.source.frequency?.value??null,startedAt:v.source.__qaStartedAt??null,endedAt:v.source.__qaEndedAt??null,peakRms:v.peakRms,peakAt:v.peakAt,rms,context:v.ctx.state};});
 window.__startContactTrace=()=>{
  const tick=async()=>{if(__cueProbe.done)return;const raw=__raw();if(raw){const status=await __tools.get_run_status({});const frame={stamp:performance.now(),screen:status.screen,run:{phase:raw.phase,time:raw.time,distance:raw.distance,lane:raw.lane,visualLane:raw.visualLane,coins:raw.coins,score:raw.score,shield:raw.shield},presentation:status.presentation??null,impact:status.renderer.impact??null,audio:status.audio,voices:__cueSnapshot()};__cueProbe.frames.push(frame);for(const effect of raw.effects)if(!__cueProbe.seen.has(effect.id)){__cueProbe.seen.add(effect.id);__cueProbe.contacts.push({...effect,stamp:frame.stamp});}}
   window.__contactRAF=requestAnimationFrame(tick);
  };window.__contactRAF=requestAnimationFrame(tick);
 };
}
const state=p=>p.evaluate(()=>__tools.get_run_status({}));
async function until(p,test,timeout=30000){const end=Date.now()+timeout;let s;while(Date.now()<end){s=await state(p);if(test(s))return s;await p.waitForTimeout(20);}throw new Error(`Timed out: ${JSON.stringify(s)}`);}
async function open(layout,reduced=false){const p=await browser.newPage({viewport:layout,reducedMotion:reduced?'reduce':'no-preference'});await p.addInitScript({content:`${audioInstall}\n${gpuInstall}\nobserveAudio();install();`});await p.addInitScript(observeCues);if(layout.name==='fallback')await p.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'||type==='webgl2'?null:original.call(this,type,...args);};});p.on('pageerror',e=>report.errors.push(e.message));if(base.includes(':3001/'))await p.route('**/arcade/quiet.js',r=>r.fulfill({contentType:'text/javascript',body:requireQuiet}));await p.goto(base);await p.waitForFunction(()=>{const b=document.querySelector('button[aria-label="Start run"]');return b&&!b.disabled;},{},{timeout:90000});const bundle=await p.evaluate(()=>[...document.scripts].map(s=>s.src).find(s=>s.includes('/river-rush/assets/index-')));if(process.env.EXPECTED_BUNDLE)assert.ok(bundle.endsWith(process.env.EXPECTED_BUNDLE));p.qaCss=await p.evaluate(()=>document.querySelector('link[href*="/river-rush/assets/index-"]')?.href??null);if(process.env.EXPECTED_CSS)assert.ok(p.qaCss.endsWith(process.env.EXPECTED_CSS));p.qaBundle=bundle;p.qaPrepared=await p.evaluate(()=>({...__resources}));return p;}
const save=async()=>fs.writeFile(`${out}/contact-${stage}.json`,JSON.stringify(report,null,2)+'\n');
try{
 const layouts=[{name:'desktop',width:1536,height:1024},{name:'phone',width:390,height:844},{name:'landscape',width:844,height:390},...(process.env.CASE==='fallback'?[{name:'fallback',width:390,height:844}]:[])];
 for(const layout of layouts){
  if(process.env.CASE&&process.env.CASE!==layout.name)continue;
  const p=await open(layout);await p.evaluate(()=>__startContactTrace());await p.getByRole('button',{name:'Start run',exact:true}).click();
  await until(p,s=>s.run?.distance>=36);const starter=await state(p);assert.equal(starter.run.coins,6);if(stage==='after')assert.equal(starter.audio.cueCounts.coin,6);
  if(process.env.SMOKE==='1'){
   const hud=await p.evaluate(()=>{const rows={};for(const selector of ['.runner-distance','.terrain-cue','.runner-notice','.gesture-guide-play','.hud-score-capture']){const r=document.querySelector(selector)?.getBoundingClientRect();if(r)rows[selector]={x:r.x,y:r.y,right:r.right,bottom:r.bottom};}return rows;});
   for(const [selector,r] of Object.entries(hud))assert.ok(r.x>=0&&r.y>=0&&r.right<=layout.width&&r.bottom<=layout.height,`${selector} must fit the viewport`);
   const screenshot=`${out}/${layout.name}-hud.png`;await p.screenshot({path:screenshot});console.log('HUD captured');
   await until(p,s=>s.run.shield===false&&s.screen==='playing');await p.keyboard.press('ArrowLeft');await until(p,s=>s.run.lane===0);await p.keyboard.press('Escape');await until(p,s=>s.screen==='paused');await p.waitForTimeout(350);const paused=await state(p),pixels=await p.locator('canvas').screenshot();console.log('Protected hit and settled pause captured');await p.waitForTimeout(100);assert.equal(JSON.stringify(await state(p)),JSON.stringify(paused),'Paused status must remain identical');assert.ok((await p.locator('canvas').screenshot()).equals(pixels),'Paused canvas pixels must remain identical');await p.getByRole('button',{name:'Resume run',exact:true}).click();await until(p,s=>s.screen==='playing');await p.keyboard.press('Escape');await until(p,s=>s.screen==='paused');await p.getByRole('button',{name:'Back to river',exact:true}).click();const home=await until(p,s=>s.screen==='menu');assert.equal(home.audio.active,false);
   const trace=await p.evaluate(()=>{__cueProbe.done=true;cancelAnimationFrame(__contactRAF);return{voices:__cueSnapshot(),resources:{...__resources},gpuErrors:__gpuErrors};});assert.deepEqual(trace.resources,p.qaPrepared);assert.deepEqual(trace.gpuErrors,[]);assert.ok(trace.voices.some(v=>v.wave==='triangle'&&v.peakRms>.01));assert.ok(trace.voices.some(v=>v.source==='noise'&&v.peakRms>.002));report.rows.push({case:'final-built-short-contact-HUD-controls-pause-resume-home',layout,bundle:p.qaBundle,css:p.qaCss,starter,hud,paused,home,voices:trace.voices,noActiveGpuPreparation:true,screenshot});await save();await p.close();continue;
  }
  await until(p,s=>s.run?.shield===false&&s.screen==='playing');await p.keyboard.press('ArrowLeft');await until(p,s=>s.run.lane===0);await p.keyboard.press('ArrowRight');await until(p,s=>s.run.lane===1);const protectedResponsive=true;
  await p.getByRole('dialog',{name:'Map ended',exact:true}).waitFor({timeout:30000});await p.evaluate(()=>{__cueProbe.done=true;cancelAnimationFrame(__contactRAF);});
  const data=await p.evaluate(()=>({frames:__cueProbe.frames,contacts:__cueProbe.contacts,voices:__cueSnapshot(),status:__tools.get_run_status({}),resources:{...__resources},gpuErrors:__gpuErrors}));data.status=await state(p);await fs.writeFile(`${out}/latest-${layout.name}.json`,JSON.stringify(data,null,2));
  const coins=data.contacts.filter(e=>e.type==='coin'),hit=data.contacts.find(e=>e.type==='hit'),lose=data.contacts.find(e=>e.type==='lose');assert.ok(hit&&lose);assert.equal(coins.filter(e=>e.distance<=32).length,6);if(stage==='after')assert.equal(data.status.audio.cueCounts.coin,coins.length,'Every physically collected coin must dispatch its sound once');assert.ok(coins.every(e=>Math.abs(e.playerLane-1)<=.25&&!e.attracted));
  let fatalFrames=[];
  if(stage==='after'){
   fatalFrames=data.frames.filter(f=>f.screen==='impact');assert.ok(fatalFrames.length>=3,'Fatal contact must display multiple wipeout frames before results');const stopped=fatalFrames[0].run;assert.ok(fatalFrames.every(f=>JSON.stringify(f.run)===JSON.stringify(stopped)),'Every fatal presentation frame must freeze engine time/distance/score/steering');assert.ok(fatalFrames.some(f=>f.impact?.active&&f.impact.fatal&&f.impact.strength>0));assert.ok(fatalFrames.some(f=>f.audio.contextState==='running'&&f.voices.some(v=>v.rms>.004)),'Fatal impact voices must have measurable audio before results');assert.ok(data.frames.some(f=>f.impact?.type==='hit'&&f.impact.recoil>0));assert.equal(data.status.audio.active,false);assert.ok(data.status.audio.activeVoices<=data.status.audio.voiceLimit);assert.ok(data.voices.some(v=>v.wave==='triangle'&&v.peakRms>.01),'Layered collision must contain an audible wood/body transient');assert.ok(data.voices.some(v=>v.source==='noise'&&v.peakRms>.002),'Collision must contain an audible splash');assert.ok(data.voices.filter(v=>v.frequency>1100&&v.wave==='sine').some(v=>v.peakRms>.01),'Coin partials must actually produce decoded audio');
  }
  assert.deepEqual(data.resources,p.qaPrepared);assert.deepEqual(data.gpuErrors,[]);const screenshot=`${out}/${stage}-${layout.name}-result.png`;await p.screenshot({path:screenshot});await p.getByRole('button',{name:'Retry Canopy Run',exact:true}).click();await until(p,s=>s.screen==='playing'&&s.run.distance>=8);const retry=await state(p);if(stage==='after'){assert.equal(retry.presentation.active,false);assert.equal(retry.presentation.fatalElapsed,0);}
  const row={layout,bundle:p.qaBundle,css:p.qaCss,starter,protectedResponsive,contacts:data.contacts,frames:data.frames.filter(f=>f.screen==='impact'||f.impact?.active).map(({voices,...frame})=>({...frame,voices:voices.filter(v=>v.rms>.0001)})),voices:data.voices,fatalFrames:fatalFrames.length,result:data.status,retry,preparedResources:p.qaPrepared,noActiveGpuPreparation:true,screenshot};report.rows.push(row);await save();console.log(JSON.stringify({layout:layout.name,stage,coins:coins.length,fatalFrames:fatalFrames.length,passed:true}));await p.close();
 }
 if(stage==='after'&&!process.env.CASE&&!process.env.SMOKE){
  const p=await open({width:390,height:844},true);await p.getByRole('button',{name:'Start run',exact:true}).click();await p.keyboard.press('ArrowLeft');await until(p,s=>s.run.distance>=36);const adjacent=await state(p);assert.equal(adjacent.run.coins,0);assert.equal(adjacent.audio.cueCounts.coin??0,0);await p.keyboard.press('Escape');await until(p,s=>s.screen==='paused');const paused=await state(p),pixels=await p.locator('canvas').screenshot();await p.waitForTimeout(150);assert.equal(JSON.stringify(await state(p)),JSON.stringify(paused),'Paused status must remain identical');assert.ok((await p.locator('canvas').screenshot()).equals(pixels),'Paused canvas pixels must remain identical');await p.getByRole('button',{name:'Resume run',exact:true}).click();await p.getByRole('button',{name:'Mute sound',exact:true}).click();const muted=await until(p,s=>!s.audio.enabled);const beforeCounts=muted.audio.cueCounts;await p.keyboard.press('ArrowRight');await until(p,s=>s.run.lane===1);await until(p,s=>s.screen==='impact');const reduced=await state(p);assert.equal(reduced.renderer.impact.cameraShake,0);assert.ok(reduced.renderer.impact.flash>0||reduced.renderer.impact.brace>0);assert.deepEqual(reduced.audio.cueCounts,beforeCounts);
  await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await until(p,s=>s.screen==='paused');const hidden=await state(p);await p.waitForTimeout(150);assert.deepEqual(await state(p),hidden);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert.equal((await state(p)).screen,'paused');await p.getByRole('button',{name:'Resume run',exact:true}).click();await p.getByRole('dialog',{name:'Map ended',exact:true}).waitFor();report.rows.push({case:'adjacent-coins-reduced-motion-mute-pause-hidden',adjacent,paused,muted,reduced,hidden});await p.close();
 }
 assert.deepEqual(report.errors,[]);report.passed=true;await save();
}finally{await save();await browser.close();}
