import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
const {chromium}=createRequire(new URL('../../games/river-rush/package.json',import.meta.url))('playwright');
const base=process.env.ARCADE_URL||'http://localhost:8765/';
const out=process.env.SHOTS||'/tmp/river-rush-meshy-qa';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']});
const errors=[],results=[];
const shim=()=>{window.__tools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.__tools[t.name]=t.execute;}}});};
const state=p=>p.evaluate(()=>window.__tools.get_run_status({}));
async function until(p,predicate){const end=Date.now()+18000;let s;while(Date.now()<end){s=await state(p);if(predicate(s))return s;await p.waitForTimeout(25);}throw new Error(`Timeout ${predicate}: ${JSON.stringify(s)}`);}
async function open(viewport={width:390,height:844},setup){const p=await browser.newPage({viewport});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(shim);await setup?.(p);await p.goto(new URL('river-rush/',base).href,{waitUntil:'networkidle'});return p;}
try{
for(const [name,viewport] of [['phone',{width:390,height:844}],['desktop',{width:1536,height:1024}],['landscape',{width:844,height:390}]]){
 const p=await open(viewport);await p.getByRole('button',{name:'Start run',exact:true}).click();const ready=await until(p,s=>s.renderer.kind==='webgl'&&Object.values(s.renderer.models).every(x=>x==='ready'));
 await p.keyboard.press('Escape');await p.getByRole('button',{name:'Restart run',exact:true}).click();assert.equal(await p.locator('.game-river-video').count(),0);assert.ok(ready.renderer.triangles>20000);assert.equal(ready.renderer.bankInstances,26);
 await p.keyboard.press('ArrowLeft');await until(p,s=>s.run.lane===0);await p.keyboard.press('ArrowRight');await until(p,s=>s.run.lane===1);
 if(name==='phone'){const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:400}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:213,y:400}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await until(p,s=>s.run.lane===2);await p.keyboard.press('ArrowLeft');}
 await until(p,s=>s.run.hint?.type==='log'&&s.run.hint.in<.4&&s.run.hint.in>.1);await p.keyboard.press('Space');await until(p,s=>s.run.action==='jump'&&s.renderer.buoyancy.lift>.1);await p.screenshot({path:`${out}/jump-${name}.png`});await until(p,s=>s.run.jumps===1);
 await until(p,s=>s.run.hint?.type==='branch'&&s.run.hint.in<.4&&s.run.hint.in>.1);await p.keyboard.press('ArrowDown');await until(p,s=>s.run.action==='duck');await p.screenshot({path:`${out}/duck-${name}.png`});await until(p,s=>s.run.ducks===1);assert.equal((await state(p)).run.shield,true);
 await p.keyboard.press('ArrowRight');await until(p,s=>s.run.lane===2);await p.screenshot({path:`${out}/ride-${name}.png`});await p.keyboard.press('Escape');await p.getByRole('dialog',{name:'Game paused'}).waitFor();await p.waitForTimeout(200);
 const paused=await state(p),pixels=await p.locator('canvas').evaluate(c=>c.toDataURL());await p.waitForTimeout(350);assert.deepEqual(await state(p),paused);assert.equal(await p.locator('canvas').evaluate(c=>c.toDataURL()),pixels);
 await p.emulateMedia({reducedMotion:'reduce'});await p.getByRole('button',{name:'Resume run'}).click();const reduced=await until(p,s=>s.renderer.reducedMotion);assert.equal(reduced.renderer.buoyancy.pitch,0);assert.equal(reduced.renderer.buoyancy.roll,0);assert.equal(reduced.renderer.buoyancy.water,0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 results.push({viewport:name,models:ready.renderer.models,triangles:ready.renderer.triangles,drawCalls:ready.renderer.drawCalls,software:ready.renderer.software,jump:true,duck:true,touch:name==='phone',pausePixels:true,reducedMotion:true});await p.close();
}
let imageAttempts=0,modelAttempts=0;
const transient=await open(undefined,async p=>{await p.route('**/art/paddle-frames.png*',r=>++imageAttempts===1?r.fulfill({status:503,body:'unavailable'}):r.continue());await p.route('**/models/meshy-raft.glb*',r=>++modelAttempts===1?r.fulfill({status:503,body:'unavailable'}):r.continue());});await transient.getByRole('button',{name:'Start run',exact:true}).click();await until(transient,s=>s.renderer.models?.raft==='ready');assert.ok(imageAttempts>=2&&modelAttempts>=2);results.push({temporary503:'recovered',imageAttempts,modelAttempts});await transient.close();
const missing=await open(undefined,p=>p.route('**/models/meshy-raft.glb*',r=>r.fulfill({status:503,body:'unavailable'})));await missing.getByRole('button',{name:'Start run',exact:true}).click();await until(missing,s=>s.renderer.models?.raft==='fallback');await missing.keyboard.press('Space');await until(missing,s=>s.run.action==='jump');results.push({missingModel:'playable'});await missing.close();
let blocked=true;const retry=await open(undefined,p=>p.route('**/art/paddle-frames.png*',r=>blocked?r.fulfill({status:503,body:'unavailable'}):r.continue()));await retry.getByRole('button',{name:'Try loading again',exact:true}).waitFor();blocked=false;await retry.getByRole('button',{name:'Try loading again',exact:true}).click();await retry.getByRole('button',{name:'Start run',exact:true}).waitFor();results.push({manualRetry:'recovered'});await retry.close();
const fallback=await open(undefined,p=>p.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...a){if(type==='webgl2'||type==='webgl')return null;return original.call(this,type,...a);};}));await fallback.getByRole('button',{name:'Start run',exact:true}).click();await fallback.keyboard.press('ArrowLeft');await until(fallback,s=>s.run.lane===0&&s.renderer.kind==='2d');await fallback.keyboard.press('Space');await until(fallback,s=>s.run.action==='jump');results.push({noWebGL:'playable2d'});await fallback.close();
const loss=await open();await loss.getByRole('button',{name:'Start run',exact:true}).click();await until(loss,s=>s.renderer.kind==='webgl');await loss.locator('canvas').evaluate(c=>c.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await loss.getByRole('dialog',{name:'Game paused'}).waitFor();await until(loss,s=>s.renderer.kind==='2d');await loss.getByRole('button',{name:'Resume run'}).click();await loss.keyboard.press('ArrowRight');await until(loss,s=>s.run.lane===2&&s.screen==='playing');results.push({contextLoss:'pausedThenPlayable2d'});await loss.close();
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,results,screenshots:out,errors}));
}finally{await browser.close();}
